### PR TITLE
Cherry pick sharded pubsub commit into 4.5

### PR DESCRIPTION
**Pull request by noah-chae**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

### CODE REVIEW

**Review by zach-iee — APPROVED** [review]
@noah-chae this one doesn't need to get merged to master, because it already has changes from 5.0?

**Comment by zach-iee** [comment]
@noah-chae i've rebased to 4.5 and fixed import order

**Comment by noah-chae** [comment]
> @noah-chae this one doesn't need to get merged to master, because it already has changes from 5.0?

Yes that's right. I missed this comment sorry for late reply

**Comment by noah-chae** [comment]
> @noah-chae i've rebased to 4.5 and fixed import order

Super thanks 🙏

**Review by bellatoris — APPROVED** [review]

**Pull request merged**
