### PR TITLE
Add lock to Pubsub.execute_command to ensure only one connection is created

### PR DESCRIPTION
**Pull request by dlunch**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

### CODE REVIEW

**Comment by dlunch** [comment]
is it better patch it upstream?

**Comment by zach-iee** [comment]
> is it better patch it upstream?

it would be best to patch the upstream as well as we can remove this PR once upstream release a new release

Also could you please add a test case for this code (ex. lock is already acquired and trying to acquire a connection doesn't return a new connection)?

**Review by zach-iee — COMMENTED** [review]
i'll review again, when a test is added

**Comment by zach-iee** [comment]
@dlunch any update?

**Comment by dlunch** [comment]
Sorry, i was on vacation. i'll add test this week

**Review by bellatoris — APPROVED** [review]

**Review by zach-iee — APPROVED** [review]
👍 
please create a PR to 4.4 branch in order to backmerge

**Pull request merged**
