### PR TITLE
[SF-11323] disallow sending command getkeys

### PR DESCRIPTION
**Pull request by bellatoris**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

_Please provide a description of the change here._

### CODE REVIEW

**Review by zach-iee — APPROVED** [review]
LGTM

4.5 and above introduced a command packer, so we would have to rewrite the code, when we plan to upgrade to 4.5

redis-py claims that 4.5 has over 25% performance boost in write
https://github.com/redis/redis-py/releases/tag/v4.5.0

**Comment by zach-iee** [comment]
please fix the style to pass the linter
https://github.com/sendbird/redis-py/actions/runs/5542821285/jobs/10118003768?pr=7

**Comment by zach-iee** [comment]
Also tests for `zdiffstore` and etc are failing, because `command getkeys` have been disabled. We can implement the same functionality in https://github.com/sendbird/soda/blob/develop/soda/cache/connection.py as a mixin if you want

**Comment by bellatoris** [comment]
> Also tests for `zdiffstore` and etc are failing, because `command getkeys` have been disabled. We can implement the same functionality in https://github.com/sendbird/soda/blob/develop/soda/cache/connection.py as a mixin if you want

I am wary about that other library which uses redis client directly crashes the redis server... So that's the why I implemented this logic here

**Comment by bellatoris** [comment]
> LGTM
> 
> 4.5 and above introduced a command packer, so we would have to rewrite the code, when we plan to upgrade to 4.5
> 
> redis-py claims that 4.5 has over 25% performance boost in write https://github.com/redis/redis-py/releases/tag/v4.5.0

Do we have plan to upgrade to 4.5?

**Comment by zach-iee** [comment]
> > LGTM
> > 4.5 and above introduced a command packer, so we would have to rewrite the code, when we plan to upgrade to 4.5
> > redis-py claims that 4.5 has over 25% performance boost in write https://github.com/redis/redis-py/releases/tag/v4.5.0
> 
> Do we have plan to upgrade to 4.5?

i was working on it without a definitive due date. The current approach doesn't hurt upgradability, but just requires a code patch.

> I am wary about that other library which uses redis client directly crashes the redis server... So that's the why I implemented this logic here

if that's the worry, the current code may be the best guarantee. If so, we can fix the tests that are failing in this repo :)

**Comment by bellatoris** [comment]
> If so, we can fix the tests that are failing in this repo :)

hmm hard to find which tests are failing due to this patch. any idea?

**Comment by zach-iee** [comment]
> Details

you can take a look at the result of the github actions

for example, https://github.com/sendbird/redis-py/actions/runs/5551140608/jobs/10136956857?pr=7 contains one of the test results. Tests that failed from `E           Exception: Redis command "COMMAND GETKEYS" is not supported` seems to be caused by this PR

**Comment by bellatoris** [comment]
> > Details
> 
> you can take a look at the result of the github actions
> 
> for example, https://github.com/sendbird/redis-py/actions/runs/5551140608/jobs/10136956857?pr=7 contains one of the test results. Tests that failed from `E Exception: Redis command "COMMAND GETKEYS" is not supported` seems to be caused by this PR

Sigh... too many

**Comment by bellatoris** [comment]
@zach-iee please review one more time

**Pull request merged**
